# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]            # auto-fix einfache Findings
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff (format)        # Formatter (ersetzt Black)
        types_or: [python, pyi]

exclude: |
  (?x)^(
    \.venv/|
    venv/|
    .*/\.venv/|
    runs/|
    data/|
    \.data/|
    .*\.csv$|
    .*\.log$
  )
