files: \.py$
exclude: |
  ^(
    \.venv/|
    venv/|
    .*/\.venv/|
    .*/venv/|
    .*/site-packages/|
    crypto-alerts_v2/\.venv/|
    crypto-alerts_v3/\.venv/|
    crypto-alerts_v3/|
    runs/|
    data/|
    .*\.csv$|
    .*\.log$
  )$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
