name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install lint deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Determine lint targets
        id: targets
        shell: bash
        run: |
          paths=""
          [ -d crypto-alerts_v2 ] && paths="$paths crypto-alerts_v2"
          [ -d scripts ] && paths="$paths scripts"
          [ -f fetch_binance_ohlcv.py ] && paths="$paths fetch_binance_ohlcv.py"
          echo "paths=$paths" >> "$GITHUB_OUTPUT"

      - name: Ruff (lint)
        if: ${{ steps.targets.outputs.paths != '' }}
        run: ruff check ${{ steps.targets.outputs.paths }}

      - name: Black (format check)
        if: ${{ steps.targets.outputs.paths != '' }}
        run: black --check ${{ steps.targets.outputs.paths }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project requirements (if any)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (only if tests/ exists)
        if: ${{ hashFiles('tests/**') != '' }}
        run: |
          python -m pip install pytest
          pytest -q
